name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Convert owner to lowercase
      run: echo "OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ghcr.io/${{ env.OWNER }}/woo-website-template-apiv2:latest
          ghcr.io/${{ env.OWNER }}/woo-website-template-apiv2:${{ github.sha }}
        # Add these lines for more verbose output
        build-args: |
          BUILDKIT_INLINE_CACHE=1
        outputs: type=docker,dest=/tmp/docker-image.tar
    
    # Add this step to see the full build log
    - name: Show Docker build log
      if: failure()
      run: |
        docker load --input /tmp/docker-image.tar
        docker history ghcr.io/${{ env.OWNER }}/woo-website-template-apiv2:latest
